### ISSUE TITLE
1.7 Profile Page [frontend]

### ISSUE THREAD

**Issue by KhalilGarali** [SOEN490-SportsApp/SportsApp#35]
## Description
As a user, I want to see my profile on a specific page, so that I can view my personal details and preferences.

Story Points: 8
Priority: 2
Risk: medium
Child Tasks:

**Comment by JRB958** [comment]
The API integration was not FULLY COMPLETE and will refactored and redesigned next iteration with new implementation using 3rd party handlers for better security
